# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool: my-personal-computer

resources:
- repo: self

variables:
   imageName: 'pipelines-javascript-docker'
   
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: /app/Dockerfile

